//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt20_praktika_
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZakazClient
    {
        public int IdZakaz { get; set; }
        public System.DateTime DateZakaz { get; set; }
        public string TovarName { get; set; }
        public string ClientName { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
    }
}
