//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt20_praktika_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaziki
    {
        public int IdZakaz { get; set; }
        public Nullable<int> AllPrice { get; set; }
    }
}
