//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prakt20_praktika_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        public int IdZakaz { get; set; }
        public System.DateTime DateZakaz { get; set; }
        public int IdClient { get; set; }
        public int IdTovar { get; set; }
        public Nullable<int> Kol { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
